name: Builds registree

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/registree-builder
      - name: Build backend
        run: mvn install
      - name: Build frontend
        run: |
          cd frontend/registree-frontend
          npm ci
